basic_settings:
  site_title: Valentina M.
  favicon_image: /images/favicon.png

header_settings:
  logo_image:
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    - title: 'Writing'
      url: '/blog/'
    - title: 'My Story'
      url: '/about'
    - title: 'Write me'
      url: '/contact'

footer_settings:
  logo_image:
  logo_width: 200
  footer_tagline: I chose to be a designer because I wanted never to be bored.

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'http://instagram.com'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: 'http://dribbble.com/ScintillaLuz'
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: 'http://bandcamp.com/scintillaluz'
  linkedin_url: 'https://www.linkedin.com/in/scintillaluz/'

color_settings:
  background_color: '#f5f5f5'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#333333'
  text_medium_color: '#4e4d4d'
  text_light_color: '#c7c7c7'
  accent_color: '#8065ec'
  border_color: '#dddddd'
  overlay_background_color: '#8065ec'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i" rel="stylesheet">'
  title_font: '"PT Serif", serif'
  body_font: '"PT Serif", serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 700
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 700
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 700
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
